name: build and upload vtk

on:
  workflow_call:
    inputs:
      version_major:
        description: 'Which VTK version (major) are we considering'
        required: true
        type: string
      version_minor:
        description: 'Which VTK version (minor) are we considering'
        required: true
        type: string
      version_patch:
        description: 'Which VTK version (patch) are we considering'
        required: true
        type: string
      shared:
        description: 'Whether shared or static libraries shall be built'
        required: true
        type: boolean
      threads:
        description: 'Number of compilation threads'
        required: false
        type: number
        default: 4
on:
  workflow_run:
    workflows: ["build and upload vtk-minimal"]
    types: 
      - completed

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  CMAKE_OPTIONS: -DVTK_BUILD_EXAMPLES=OFF -DVTK_BUILD_TESTING=OFF -DCMAKE_VERBOSE_MAKEFILE=ON
  VTK_MODULES: -DVTK_GROUP_ENABLE_Imaging=YES -DVTK_GROUP_ENABLE_Qt=NO -DVTK_GROUP_ENABLE_Rendering=YES -DVTK_GROUP_ENABLE_Views=YES -DVTK_GROUP_ENABLE_Web=NO
  BUILD_TYPE: Release

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v3

    - name: Determine release name
      uses: haya14busa/action-cond@v1
      id: release-name
      with:
        cond: ${{ inputs.shared }}
        if_true: VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}-shared
        if_false: VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}-static

    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: ${{ steps.release-name.outputs.value }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: rickstaa/action-create-tag@v1
      id: create_tag
      with:
        tag: ${{ steps.release-name.outputs.value }}
        message: ${{ steps.release-name.outputs.value }}
        force_push_tag: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release-name.outputs.value }}
        release_name: ${{ steps.release-name.outputs.value }}
        draft: false
        prerelease: false

  build:
    runs-on: ${{ matrix.os }}
    needs: [create_release]
    strategy:
        matrix:
            os: [ubuntu-22.04, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: download VTK
      uses: suisei-cn/actions-download-file@v1.0.1
      with:
        url: https://vtk.org/files/release/${{ inputs.version_major }}.${{ inputs.version_minor }}/VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}.tar.gz
        target: ${{github.workspace}}/

    - name: Extract VTK tgz
      run: |
          tar -xvzf VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}.tar.gz
    
    - name: List files
      run: |
          ls ${{github.workspace}}
    
    - name: Create installation folder
      run: |
          mkdir -p ${{github.workspace}}/install

    - uses: actions/setup-python@v3

    - name: Install dependencies (Linux)
      run: sudo apt update && sudo apt install libopenmpi-dev libopengl-dev libglx-dev libglw-dev
      if: runner.os == 'Linux'

    - name: BUILD_SHARED_LIBS value
      uses: haya14busa/action-cond@v1
      id: BUILD_SHARED_LIBS
      with:
        cond: ${{ inputs.shared }}
        if_true: -DBUILD_SHARED_LIBS=ON
        if_false: -DBUILD_SHARED_LIBS=OFF

    - name: Configure CMake (Linux)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{env.CMAKE_OPTIONS}} ${{env.VTK_MODULES}} ${{ steps.BUILD_SHARED_LIBS.outputs.value }} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}
      if: runner.os == 'Linux'

    - name: Configure CMake (Windows)
      run: cmake -B ${{github.workspace}}/build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{env.CMAKE_OPTIONS}} ${{env.VTK_MODULES}} ${{ steps.BUILD_SHARED_LIBS.outputs.value }} -DVTK_MODULE_ENABLE_VTK_tiff=NO -DVTK_MODULE_ENABLE_VTK_netcdf=NO -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}
      if: runner.os == 'Windows'

    - name: Configure CMake (MacOS)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ${{env.CMAKE_OPTIONS}} ${{env.VTK_MODULES}} ${{ steps.BUILD_SHARED_LIBS.outputs.value }} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install VTK-${{ inputs.version_major }}.${{ inputs.version_minor }}.${{ inputs.version_patch }}
      if: runner.os == 'MacOS'

    - name: Build
      id: build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j ${{inputs.threads}}

    - name: Install
      working-directory: ${{github.workspace}}/build
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Create tar.gz
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ${{github.workspace}}/install
        files: ./
        outPath: ${{github.workspace}}/vtk-${{ runner.os }}-x86_64.tar.gz

    - name: Upload tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/vtk-${{ runner.os }}-x86_64.tar.gz
        asset_name: vtk-${{ runner.os }}-x86_64.tar.gz
        asset_content_type: application/zip

  build_multiarch:
    runs-on: ubuntu-22.04
    needs: [create_release]
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu22.04
          - arch: aarch64
            distro: ubuntu22.04
          - arch: s390x
            distro: ubuntu22.04
          - arch: ppc64le
            distro: ubuntu22.04

    steps:
    - uses: actions/checkout@v2.1.0

    - name: BUILD_SHARED_LIBS value
      uses: haya14busa/action-cond@v1
      id: BUILD_SHARED_LIBS
      with:
        cond: ${{ inputs.shared }}
        if_true: -DBUILD_SHARED_LIBS=ON
        if_false: -DBUILD_SHARED_LIBS=OFF

    - name: Create folders
      run: |
          mkdir -p ${PWD}/artifacts/build
          mkdir -p ${PWD}/artifacts/install

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if the artifact is from a different repo
        # Required, if the repo is private a Personal Access Token with `repo` scope is needed
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Optional, workflow file name or ID
        # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
        workflow: minimal.yml
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        # Use the empty string ("") to ignore status or conclusion in the search
        workflow_conclusion: success
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them into respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        name: Compilation environment for ${{ matrix.arch }}
        # Optional, a directory where to extract artifact(s), defaults to the current directory
        path: ${PWD}/artifacts/
        # Optional, check the workflow run to whether it has an artifact
        # then will get the last available artifact from the previous workflow
        # default false, just try to download from the last one
        check_artifacts:  false
        # Optional, search for the last workflow run whose stored an artifact named as in `name` input
        # default false
        search_artifacts: false
        # Optional, choose to skip unpacking the downloaded artifact(s)
        # default false
        skip_unpack: true
        # Optional, choose how to exit the action if no artifact is found
        # can be one of:
        #  "fail", "warn", "ignore"
        # default fail
        if_no_artifact_found: fail

    - name: Extract VTK tgz
      run: |
          tar -xvzf ${PWD}/artifacts/vtk-Linux-${{ matrix.arch }}.tar.gz -C ${PWD}/artifacts/
    
    - name: List files
      run: |
          ls ${PWD}/artifacts/

    - name: Build
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: ${{ matrix.arch }}
        distro: ${{ matrix.distro }}

        # Not required, but speeds up builds
        githubToken: ${{ github.token }}

        # Mount the artifacts directory as /artifacts in the container
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"

        # Pass some environment variables to the container
        env: | # YAML, but pipe character is necessary
          version_major: ${{ inputs.version_major }}
          version_minor: ${{ inputs.version_minor }}
          version_patch: ${{ inputs.version_patch }}
          threads: ${{ inputs.threads }}
          BUILD_TYPE: ${{ env.BUILD_TYPE }}            
          CMAKE_OPTIONS: ${{ env.CMAKE_OPTIONS }} ${{env.VTK_MODULES}} ${{ steps.BUILD_SHARED_LIBS.outputs.value }}

        shell: /bin/sh

        # Install some dependencies in the container. This speeds up builds if
        # you are also using githubToken. Any dependencies installed here will
        # be part of the container image that gets cached, so subsequent
        # builds don't have to re-install them. The image layer is cached
        # publicly in your project's package repository, so it is vital that
        # no secrets are present in the container state or logs.
        install: |
          apt-get update -q -y
          apt-get install -q -y build-essential cmake curl libopenmpi-dev libopengl-dev libglx-dev libglw-dev

        run: |
          cmake -B /artifacts/build -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${CMAKE_OPTIONS} -DCMAKE_INSTALL_PREFIX=/artifacts/install /artifacts/VTK-${version_major}.${version_minor}.${version_patch}
          cmake --build /artifacts/build --config ${BUILD_TYPE} -j ${threads}
          cmake --install /artifacts/build --config ${BUILD_TYPE}

    - name: Create tar.gz
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ${PWD}/artifacts/install/
        files: ./
        outPath: ${{github.workspace}}/vtk-Linux-${{ matrix.arch }}.tar.gz

    - name: Upload tar.gz
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/vtk-Linux-${{ matrix.arch }}.tar.gz
        asset_name: vtk-Linux-${{ matrix.arch }}.tar.gz
        asset_content_type: application/zip
