name: VTK-9.3.1

on:
  push:
    branches: [ main ]

jobs:
  shared:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@main
    with:
      version_major: 9
      version_minor: 3
      version_patch: 1
      shared: true
    secrets: inherit
