name: VTK-9.2.6

on:
  push:
    branches: [ main, manylinux ]

jobs:
  shared:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@manylinux
    with:
      version_major: 9
      version_minor: 2
      version_patch: 6
      shared: true
    secrets: inherit
  static:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@manylinux
    with:
      version_major: 9
      version_minor: 2
      version_patch: 6
      shared: false
    secrets: inherit
