name: VTK-9.2.6

on:
  push:
    branches: [ main ]

jobs:
  shared:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@main
    with:
      version_major: 9
      version_minor: 3
      version_patch: "0.rc1"
      shared: true
    secrets: inherit
  static:
    uses: sanguinariojoe/vtk-builds/.github/workflows/builder.yml@main
    with:
      version_major: 9
      version_minor: 3
      version_patch: "0.rc1"
      shared: false
    secrets: inherit
